runtime: nodejs18
service: default

env_variables:
  NODE_ENV: "production"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /.*
    script: auto
    secure: always 